parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
#            $queryBus: '@tactician.commandbus.query'
#            $commandBus: '@tactician.commandbus.command'
            $eventBus: '@broadway.event_handling.event_bus'

            $eventStore: '@broadway.event_store.dbal'

    _instanceof:

        App\Application\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: command }

        App\Application\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: query }

        Broadway\EventHandling\EventListener:
            public: true
            tags:
                - { name: broadway.domain.event_listener }

    App\:
        resource: '../src/*'
        exclude: '../src/**/{Migrations,EventSubscriber}'